-- ─────────────────────────────────────────────────────────────
-- CRP (College Readiness Program) — schema init
-- Run this in the Supabase SQL editor. Additive only; drops nothing.
-- Safe to re-run (guards on enums/tables).
-- ─────────────────────────────────────────────────────────────

-- 1. Enums ------------------------------------------------------
do $$ begin
  create type public.crp_round as enum ('SCEA', 'ED', 'ED2', 'EA', 'RD', 'ROLLING');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.crp_essay_scope as enum ('shared', 'school');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.crp_essay_status as enum
    ('not_started', 'drafting', 'revising', 'reviewer_sent', 'final', 'submitted');
exception when duplicate_object then null; end $$;

-- 2. Tables -----------------------------------------------------
create table if not exists public.crp_participants (
  id           bigint generated by default as identity primary key,
  student_id   bigint      not null unique references public.students(id) on delete cascade,
  appointed_by bigint      not null references public.admin(id) on delete cascade,
  appointed_at timestamptz not null default now(),
  active       boolean     not null default true
);
create index if not exists idx_crp_participants_active on public.crp_participants(active);

create table if not exists public.crp_colleges (
  id           bigint generated by default as identity primary key,
  scorecard_id text unique,
  name         text not null,
  city         text,
  state        text,
  domain       text,
  logo_url     text,
  created_at   timestamptz not null default now()
);

create table if not exists public.crp_applications (
  id            bigint generated by default as identity primary key,
  student_id    bigint      not null references public.students(id) on delete cascade,
  college_id    bigint      not null references public.crp_colleges(id) on delete cascade,
  round         public.crp_round,
  deadline      date,
  submitted     boolean     not null default false,
  finaid_status text,
  scores_status text,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists idx_crp_applications_student on public.crp_applications(student_id);

create table if not exists public.crp_essays (
  id             bigint generated by default as identity primary key,
  student_id     bigint      not null references public.students(id) on delete cascade,
  application_id bigint      references public.crp_applications(id) on delete cascade,
  scope          public.crp_essay_scope   not null default 'school',
  type           text        not null,
  prompt         text,
  words          text,
  status         public.crp_essay_status  not null default 'not_started',
  draft_link     text,
  due            date,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists idx_crp_essays_student on public.crp_essays(student_id);
create index if not exists idx_crp_essays_status  on public.crp_essays(status);

create table if not exists public.crp_recommendations (
  id          bigint generated by default as identity primary key,
  student_id  bigint      not null references public.students(id) on delete cascade,
  recommender text        not null,
  role        text,
  for_schools text,
  requested   boolean     not null default false,
  brag_sheet  boolean     not null default false,
  submitted   boolean     not null default false,
  notes       text,
  created_at  timestamptz not null default now()
);
create index if not exists idx_crp_recommendations_student on public.crp_recommendations(student_id);

create table if not exists public.crp_tasks (
  id         bigint generated by default as identity primary key,
  student_id bigint      not null references public.students(id) on delete cascade,
  task       text        not null,
  area       text,
  priority   public.priority,
  due        date,
  done       boolean     not null default false,
  notes      text,
  created_at timestamptz not null default now()
);
create index if not exists idx_crp_tasks_student on public.crp_tasks(student_id);

-- 3. Lock down PostgREST exposure -------------------------------
-- The app reaches these tables through Prisma (direct connection, bypasses RLS).
-- Enabling RLS with no policies keeps them invisible to the anon/authenticated
-- REST API — matching how the rest of this project's tables behave.
alter table public.crp_participants    enable row level security;
alter table public.crp_colleges        enable row level security;
alter table public.crp_applications    enable row level security;
alter table public.crp_essays          enable row level security;
alter table public.crp_recommendations enable row level security;
alter table public.crp_tasks           enable row level security;
