
[functions.send_welcome_email]
enabled = true
verify_jwt = true
import_map = "./functions/send_welcome_email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send_welcome_email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send_welcome_email/*.html" ]

[functions.send_bulk_emails]
enabled = true
verify_jwt = true
import_map = "./functions/send_bulk_emails/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send_bulk_emails/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send_bulk_emails/*.html" ]

[functions.send_opportunity_accepted]
enabled = true
verify_jwt = true
import_map = "./functions/send_opportunity_accepted/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send_opportunity_accepted/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send_opportunity_accepted/*.html" ]
